### GET request with a header

GET localhost:4000/tasks

Accept: application/json
Content-Type: application/json

### POST
# curl localhost:4000/tasks

POST localhost:4000/tasks

Accept: application/json
Content-Type: application/json

{
  "title": "created task",
  "done": true,
  "due_date": "2022-10-14",
  "description": "some desc",
  "list_id": 1
}

### PARTIAL UPDATE
# curl -X PATCH localhost:4000/tasks

PATCH localhost:4000/tasks/17

Accept: application/json
Content-Type: application/json

{
  "title": "Changed",
  "done": false,
  "due_date": "2022-08-13",
  "list_id": 2,
  "description": "changed"
}

### FULL UPDATE
# curl -X PUT localhost:4000/tasks/14

PUT localhost:4000/tasks/17

Accept: application/json
Content-Type: application/json

{
  "title": "put change",
  "due_date": "2022-08-14",
  "description": "already put"
}

### DELETE
# curl -X DELETE localhost:4000/tasks/14

DELETE localhost:4000/tasks/19

Accept: application/json
Content-Type: application/json

### COUNT TODAY TASKS & LIST NAME
# curl localhost:4000/dashboard

GET localhost:4000/dashboard

Accept: application/json
Content-Type: application/json

### TASKS ON TODAY
# curl localhost:4000/collections/today

GET localhost:4000/collections/today

Accept: application/json
Content-Type: application/json

### QUERY REQUEST ONLY ALL=TRUE
# curl localhost:4000/lists/3/tasks
# curl localhost:4000/lists/3/tasks?all=true

GET localhost:4000/lists/2/tasks

Accept: application/json
Content-Type: application/json








### LISTS SEQUELIZE GET
GET http://localhost:4000/api/collection/today
# curl http://localhost:4000/api/collection/today

Accept: application/json
Content-Type: application/json

### LISTS SEQUELIZE POST
POST http://localhost:4000/api/lists

# curl localhost:4000/api/lists -d '{"name": "already put" }' -H "Content-Type: application/json"

Accept: application/json
Content-Type: application/json

{
  "name": "List created"
}

### DELETE LISTS
DELETE localhost:4000/api/lists/16

# curl -X DELETE localhost:4000/api/lists/14

Accept: application/json
Content-Type: application/json

### UPDATE LISTS
PUT http://localhost:4000/api/lists/8

# curl -X PUT localhost:4000/api/lists/6 -d '{"name": "Changed"}' -H "Content-Type: application/json"

Accept: application/json
Content-Type: application/json

{
  "name": "put change"
}